export const practiceAreas = [
  { value: 1, label: "personal", trigger: "7" },
  { value: 10, label: "Labour & Service", trigger: "7" },
  { value: 11, label: "Corporate Law", trigger: "7" },
  { value: 12, label: "Arbitration", trigger: "7" },
  { value: 13, label: "Trademark & Copyright", trigger: "7" },
  { value: 14, label: "Customs & Central Excise", trigger: "7" },
  { value: 15, label: "Startup", trigger: "7" },
  { value: 16, label: "Banking", trigger: "7" },
  { value: 17, label: "Finance", trigger: "7" },
  { value: 18, label: "GST", trigger: "7" },
  { value: 19, label: "Corporate", trigger: "7" },
  { value: 2, label: "Divorce", trigger: "7" },
  { value: 20, label: "Tax", trigger: "7" },
  { value: 21, label: "Civil", trigger: "7" },
  { value: 22, label: "Debt Matters", trigger: "7" },
  { value: 23, label: "Documentation", trigger: "7" },
  { value: 24, label: "Consumer Court", trigger: "7" },
  { value: 25, label: "Civil", trigger: "7" },
  { value: 26, label: "Cheque Bounce", trigger: "7" },
  { value: 27, label: "Recovery", trigger: "7" },
  { value: 28, label: "Property", trigger: "7" },
  { value: 29, label: "Criminal", trigger: "7" },
  { value: 3, label: "Family Dispute", trigger: "7" },
  { value: 30, label: "Landlord", trigger: "7" },
  { value: 31, label: "Tenant", trigger: "7" },
  { value: 32, label: "Cyber Crime", trigger: "7" },
  { value: 33, label: "Others", trigger: "7" },
  { value: 34, label: "Armed Forces Tribunal", trigger: "7" },
  { value: 35, label: "Insurance", trigger: "7" },
  { value: 36, label: "Immigration", trigger: "7" },
  { value: 37, label: "International Law", trigger: "7" },
  { value: 4, label: "Child Custody", trigger: "7" },
  { value: 5, label: "Muslim Law", trigger: "7" },
  { value: 6, label: "Medical Negligence", trigger: "7" },
  { value: 7, label: "Motor Accident", trigger: "7" },
  { value: 8, label: "Wills", trigger: "7" },
  { value: 9, label: "Trusts", trigger: "7" },
];
