export const courtNames = {
  1: "Allaahbad High Court",
  10: "Jammu &amp; Kashmir High Court",
  11: "Jharkhand High Court",
  12: "Karnataka High Court",
  13: "Kerala High Court",
  14: "Madhya Pradesh High Court",
  15: "Madras High Court",
  16: "Manipur High Court",
  17: "Meghalaya High Court",
  18: "Orrisa High Court",
  19: "Patna High Court",
  2: "Andhra Pradesh High Court",
  20: "Punjab and Haryana High Court",
  21: "Rajasthan High Court",
  22: "Sikkim High Court",
  23: "Telangana High Court",
  24: "Tripura High Court",
  25: "Uttarakhand High Court",
  3: "Bombay High Court",
  4: "Calcutta High Court",
  5: "Chhattisgarh High Court",
  6: "Delhi High Court",
  7: "Gauhati High Court",
  8: "Gujarat High Court",
  9: "Himachal High Court",
};
