export const languages = {
  1: "Assamese",
  10: "Maithili",
  11: "Malayalam",
  12: "Manipuri",
  13: "Marathi",
  14: "Nepali",
  15: "Oriya",
  16: "Punjabi",
  17: "Sanskrit",
  18: "Santali",
  19: "Sindhi",
  2: "Bengali",
  20: "Tamil",
  21: "Telgu",
  22: "Urdu",
  3: "Bodo",
  4: "Dogri",
  5: "English",
  6: "Hindi",
  7: "Kannada",
  8: "Kashmiri",
  9: "Konkani",
};
