export const practiceAreas = {
  1: "Personal",
  10: "Labour & Service",
  11: "Corporate Law",
  12: "Arbitration",
  13: "Trademark & Copyright",
  14: "Customs & Central Excise",
  15: "Startup",
  16: "Banking",
  17: "Finance",
  18: "GST",
  19: "Corporate",
  2: "Divorce",
  20: "Tax",
  21: "Civil",
  22: "Debt Matters",
  23: "Documentation",
  24: "Consumer Court",
  25: "Civil",
  26: "Cheque Bounce",
  27: "Recovery",
  28: "Property",
  29: "Criminal",
  3: "Family Dispute",
  30: "Landlord",
  31: "Tenant",
  32: "Cyber Crime",
  33: "Others",
  34: "Armed Forces Tribunal",
  35: "Insurance",
  36: "Immigration",
  37: "International Law",
  4: "Child Custody",
  5: "Muslim Law",
  6: "Medical Negligence",
  7: "Motor Accident",
  8: "Wills",
  9: "Trusts",
};
