export const states = {
  " Agra": " Agra",
  " Bulandshahr": " Bulandshahr",
  " Farrukhabad": " Farrukhabad",
  " Ghazipur": " Ghazipur",
  " Hardoi": " Hardoi",
  " India": " India",
  " Purulia": " Purulia",
  " Rampur": " Rampur",
  "Andaman & Nicobar Islands": "Andaman & Nicobar Islands",
  "Andhra Pradesh": "Andhra Pradesh",
  "Andhra pradesh": "Andhra pradesh",
  "Arunachal Pradesh": "Arunachal Pradesh",
  Assam: "Assam",
  Bihar: "Bihar",
  Chhattisgarh: "Chhattisgarh",
  "Dadra & Nagar Haveli": "Dadra & Nagar Haveli",
  "Daman & Diu": "Daman & Diu",
  Delhi: "Delhi",
  Goa: "Goa",
  Gujarat: "Gujarat",
  Gujrat: "Gujrat",
  Hariyana: "Hariyana",
  Haryana: "Haryana",
  "Himachal Pradesh": "Himachal Pradesh",
  "Jammu & Kashmir": "Jammu & Kashmir",
  Jharkhand: "Jharkhand",
  Karnataka: "Karnataka",
  Kerala: "Kerala",
  Lakshadweep: "Lakshadweep",
  "Madhya Pradesh": "Madhya Pradesh",
  Maharashtra: "Maharashtra",
  Maharastra: "Maharastra",
  Manipur: "Manipur",
  Meghalaya: "Meghalaya",
  Mizoram: "Mizoram",
  Nagaland: "Nagaland",
  Orissa: "Orissa",
  Pondicherry: "Pondicherry",
  Punjab: "Punjab",
  Rajastan: "Rajastan",
  Rajasthan: "Rajasthan",
  Sikkim: "Sikkim",
  "Tamil Nadu": "Tamil Nadu",
  "Tamil nadu": "Tamil nadu",
  Tripura: "Tripura",
  "Uttar Pradesh": "Uttar Pradesh",
  Uttarakhand: "Uttarakhand",
  "West Bengal": "West Bengal",
};
