package seeds

import (
	"github.com/Practicum-1/lawyer-client-backend.git/models"
)

func SeedLocations() {
	var count int64
	DB.Model(&models.Location{}).Count(&count)
	if count == 0 {
		DB.Model(&models.Location{}).Create(locations)
	}
}

var locations []models.Location = []models.Location{
	{City: "Kolhapur", State: "Maharashtra"},
	{City: "Port Blair", State: "Andaman & Nicobar Islands"},
	{City: "Adilabad", State: "Andhra Pradesh"},
	{City: "Adoni", State: "Andhra Pradesh"},
	{City: "Amadalavalasa", State: "Andhra Pradesh"},
	{City: "Amalapuram", State: "Andhra Pradesh"},
	{City: "Anakapalle", State: "Andhra Pradesh"},
	{City: "Anantapur", State: "Andhra Pradesh"},
	{City: "Badepalle", State: "Andhra Pradesh"},
	{City: "Banganapalle", State: "Andhra Pradesh"},
	{City: "Bapatla", State: "Andhra Pradesh"},
	{City: "Bellampalle", State: "Andhra Pradesh"},
	{City: "Bethamcherla", State: "Andhra Pradesh"},
	{City: "Bhadrachalam", State: "Andhra Pradesh"},
	{City: "Bhainsa", State: "Andhra Pradesh"},
	{City: "Bheemunipatnam", State: "Andhra Pradesh"},
	{City: "Bhimavaram", State: "Andhra Pradesh"},
	{City: "Bhongir", State: "Andhra Pradesh"},
	{City: "Bobbili", State: "Andhra Pradesh"},
	{City: "Bodhan", State: "Andhra Pradesh"},
	{City: "Chilakaluripet", State: "Andhra Pradesh"},
	{City: "Chirala", State: "Andhra Pradesh"},
	{City: "Chittoor", State: "Andhra Pradesh"},
	{City: "Cuddapah", State: "Andhra Pradesh"},
	{City: "Devarakonda", State: "Andhra Pradesh"},
	{City: "Dharmavaram", State: "Andhra Pradesh"},
	{City: "Eluru", State: "Andhra Pradesh"},
	{City: "Farooqnagar", State: "Andhra Pradesh"},
	{City: "Gadwal", State: "Andhra Pradesh"},
	{City: "Gooty", State: "Andhra Pradesh"},
	{City: "Gudivada", State: "Andhra Pradesh"},
	{City: "Gudur", State: "Andhra Pradesh"},
	{City: "Guntakal", State: "Andhra Pradesh"},
	{City: "Guntur", State: "Andhra Pradesh"},
	{City: "Hanuman Junction", State: "Andhra Pradesh"},
	{City: "Hindupur", State: "Andhra Pradesh"},
	{City: "Hyderabad", State: "Andhra Pradesh"},
	{City: "Ichchapuram", State: "Andhra Pradesh"},
	{City: "Jaggaiahpet", State: "Andhra Pradesh"},
	{City: "Jagtial", State: "Andhra Pradesh"},
	{City: "Jammalamadugu", State: "Andhra Pradesh"},
	{City: "Jangaon", State: "Andhra Pradesh"},
	{City: "Kadapa", State: "Andhra Pradesh"},
	{City: "Kadiri", State: "Andhra Pradesh"},
	{City: "Kagaznagar", State: "Andhra Pradesh"},
	{City: "Kakinada", State: "Andhra Pradesh"},
	{City: "Kalyandurg", State: "Andhra Pradesh"},
	{City: "Kamareddy", State: "Andhra Pradesh"},
	{City: "Kandukur", State: "Andhra Pradesh"},
	{City: "Karimnagar", State: "Andhra Pradesh"},
	{City: "Kavali", State: "Andhra Pradesh"},
	{City: "Khammam", State: "Andhra Pradesh"},
	{City: "Koratla", State: "Andhra Pradesh"},
	{City: "Kothagudem", State: "Andhra Pradesh"},
	{City: "Kothapeta", State: "Andhra Pradesh"},
	{City: "Kovvur", State: "Andhra Pradesh"},
	{City: "Kurnool", State: "Andhra Pradesh"},
	{City: "Kyathampalle", State: "Andhra Pradesh"},
	{City: "Macherla", State: "Andhra Pradesh"},
	{City: "Machilipatnam", State: "Andhra Pradesh"},
	{City: "Madanapalle", State: "Andhra Pradesh"},
	{City: "Mahbubnagar", State: "Andhra Pradesh"},
	{City: "Mancherial", State: "Andhra Pradesh"},
	{City: "Mandamarri", State: "Andhra Pradesh"},
	{City: "Mandapeta", State: "Andhra Pradesh"},
	{City: "Manuguru", State: "Andhra Pradesh"},
	{City: "Markapur", State: "Andhra Pradesh"},
	{City: "Medak", State: "Andhra Pradesh"},
	{City: "Miryalaguda", State: "Andhra Pradesh"},
	{City: "Mogalthur", State: "Andhra Pradesh"},
	{City: "Nagari", State: "Andhra Pradesh"},
	{City: "Nagarkurnool", State: "Andhra Pradesh"},
	{City: "Nandyal", State: "Andhra Pradesh"},
	{City: "Narasapur", State: "Andhra Pradesh"},
	{City: "Narasaraopet", State: "Andhra Pradesh"},
	{City: "Narayanpet", State: "Andhra Pradesh"},
	{City: "Narsipatnam", State: "Andhra Pradesh"},
	{City: "Nellore", State: "Andhra Pradesh"},
	{City: "Nidadavole", State: "Andhra Pradesh"},
	{City: "Nirmal", State: "Andhra Pradesh"},
	{City: "Nizamabad", State: "Andhra Pradesh"},
	{City: "Nuzvid", State: "Andhra Pradesh"},
	{City: "Ongole", State: "Andhra Pradesh"},
	{City: "Palacole", State: "Andhra Pradesh"},
	{City: "Palasa Kasibugga", State: "Andhra Pradesh"},
	{City: "Palwancha", State: "Andhra Pradesh"},
	{City: "Parvathipuram", State: "Andhra Pradesh"},
	{City: "Pedana", State: "Andhra Pradesh"},
	{City: "Peddapuram", State: "Andhra Pradesh"},
	{City: "Pithapuram", State: "Andhra Pradesh"},
	{City: "Pondur", State: "Andhra pradesh"},
	{City: "Ponnur", State: "Andhra Pradesh"},
	{City: "Proddatur", State: "Andhra Pradesh"},
	{City: "Punganur", State: "Andhra Pradesh"},
	{City: "Puttur", State: "Andhra Pradesh"},
	{City: "Rajahmundry", State: "Andhra Pradesh"},
	{City: "Rajam", State: "Andhra Pradesh"},
	{City: "Ramachandrapuram", State: "Andhra Pradesh"},
	{City: "Ramagundam", State: "Andhra Pradesh"},
	{City: "Rayachoti", State: "Andhra Pradesh"},
	{City: "Rayadurg", State: "Andhra Pradesh"},
	{City: "Renigunta", State: "Andhra Pradesh"},
	{City: "Repalle", State: "Andhra Pradesh"},
	{City: "Sadasivpet", State: "Andhra Pradesh"},
	{City: "Salur", State: "Andhra Pradesh"},
	{City: "Samalkot", State: "Andhra Pradesh"},
	{City: "Sangareddy", State: "Andhra Pradesh"},
	{City: "Sattenapalle", State: "Andhra Pradesh"},
	{City: "Siddipet", State: "Andhra Pradesh"},
	{City: "Singapur", State: "Andhra Pradesh"},
	{City: "Sircilla", State: "Andhra Pradesh"},
	{City: "Srikakulam", State: "Andhra Pradesh"},
	{City: "Srikalahasti", State: "Andhra Pradesh"},
	{City: "Suryapet", State: "Andhra Pradesh"},
	{City: "Tadepalligudem", State: "Andhra Pradesh"},
	{City: "Tadpatri", State: "Andhra Pradesh"},
	{City: "Tandur", State: "Andhra Pradesh"},
	{City: "Tanuku", State: "Andhra Pradesh"},
	{City: "Tenali", State: "Andhra Pradesh"},
	{City: "Tirupati", State: "Andhra Pradesh"},
	{City: "Tuni", State: "Andhra Pradesh"},
	{City: "Uravakonda", State: "Andhra Pradesh"},
	{City: "Venkatagiri", State: "Andhra Pradesh"},
	{City: "Vicarabad", State: "Andhra Pradesh"},
	{City: "Vijayawada", State: "Andhra Pradesh"},
	{City: "Vinukonda", State: "Andhra Pradesh"},
	{City: "Visakhapatnam", State: "Andhra Pradesh"},
	{City: "Vizianagaram", State: "Andhra Pradesh"},
	{City: "Wanaparthy", State: "Andhra Pradesh"},
	{City: "Warangal", State: "Andhra Pradesh"},
	{City: "Yellandu", State: "Andhra Pradesh"},
	{City: "Yemmiganur", State: "Andhra Pradesh"},
	{City: "Yerraguntla", State: "Andhra Pradesh"},
	{City: "Zahirabad", State: "Andhra Pradesh"},
	{City: "Rajampet", State: "Andhra Pradesh"},
	{City: "Along", State: "Arunachal Pradesh"},
	{City: "Bomdila", State: "Arunachal Pradesh"},
	{City: "Itanagar", State: "Arunachal Pradesh"},
	{City: "Naharlagun", State: "Arunachal Pradesh"},
	{City: "Pasighat", State: "Arunachal Pradesh"},
	{City: "Abhayapuri", State: "Assam"},
	{City: "Amguri", State: "Assam"},
	{City: "Anandnagaar", State: "Assam"},
	{City: "Barpeta", State: "Assam"},
	{City: "Barpeta Road", State: "Assam"},
	{City: "Bilasipara", State: "Assam"},
	{City: "Bongaigaon", State: "Assam"},
	{City: "Dhekiajuli", State: "Assam"},
	{City: "Dhubri", State: "Assam"},
	{City: "Dibrugarh", State: "Assam"},
	{City: "Digboi", State: "Assam"},
	{City: "Diphu", State: "Assam"},
	{City: "Dispur", State: "Assam"},
	{City: "Gauripur", State: "Assam"},
	{City: "Goalpara", State: "Assam"},
	{City: "Golaghat", State: "Assam"},
	{City: "Guwahati", State: "Assam"},
	{City: "Haflong", State: "Assam"},
	{City: "Hailakandi", State: "Assam"},
	{City: "Hojai", State: "Assam"},
	{City: "Jorhat", State: "Assam"},
	{City: "Karimganj", State: "Assam"},
	{City: "Kokrajhar", State: "Assam"},
	{City: "Lanka", State: "Assam"},
	{City: "Lumding", State: "Assam"},
	{City: "Mangaldoi", State: "Assam"},
	{City: "Mankachar", State: "Assam"},
	{City: "Margherita", State: "Assam"},
	{City: "Mariani", State: "Assam"},
	{City: "Marigaon", State: "Assam"},
	{City: "Nagaon", State: "Assam"},
	{City: "Nalbari", State: "Assam"},
	{City: "North Lakhimpur", State: "Assam"},
	{City: "Rangia", State: "Assam"},
	{City: "Sibsagar", State: "Assam"},
	{City: "Silapathar", State: "Assam"},
	{City: "Silchar", State: "Assam"},
	{City: "Tezpur", State: "Assam"},
	{City: "Tinsukia", State: "Assam"},
	{City: "Amarpur", State: "Bihar"},
	{City: "Araria", State: "Bihar"},
	{City: "Areraj", State: "Bihar"},
	{City: "Arrah", State: "Bihar"},
	{City: "Asarganj", State: "Bihar"},
	{City: "Aurangabad", State: "Bihar"},
	{City: "Bagaha", State: "Bihar"},
	{City: "Bahadurganj", State: "Bihar"},
	{City: "Bairgania", State: "Bihar"},
	{City: "Bakhtiarpur", State: "Bihar"},
	{City: "Banka", State: "Bihar"},
	{City: "Banmankhi Bazar", State: "Bihar"},
	{City: "Barahiya", State: "Bihar"},
	{City: "Barauli", State: "Bihar"},
	{City: "Barbigha", State: "Bihar"},
	{City: "Barh", State: "Bihar"},
	{City: "Begusarai", State: "Bihar"},
	{City: "Behea", State: "Bihar"},
	{City: "Bettiah", State: "Bihar"},
	{City: "Bhabua", State: "Bihar"},
	{City: "Bhagalpur", State: "Bihar"},
	{City: "Bihar Sharif", State: "Bihar"},
	{City: "Bikramganj", State: "Bihar"},
	{City: "Bodh Gaya", State: "Bihar"},
	{City: "Buxar", State: "Bihar"},
	{City: "Chandan Bara", State: "Bihar"},
	{City: "Chanpatia", State: "Bihar"},
	{City: "Chhapra", State: "Bihar"},
	{City: "Colgong", State: "Bihar"},
	{City: "Dalsinghsarai", State: "Bihar"},
	{City: "Darbhanga", State: "Bihar"},
	{City: "Daudnagar", State: "Bihar"},
	{City: "Dehri-on-Sone", State: "Bihar"},
	{City: "Dhaka", State: "Bihar"},
	{City: "Dighwara", State: "Bihar"},
	{City: "Dumraon", State: "Bihar"},
	{City: "Fatwah", State: "Bihar"},
	{City: "Forbesganj", State: "Bihar"},
	{City: "Gaya", State: "Bihar"},
	{City: "Gogri Jamalpur", State: "Bihar"},
	{City: "Gopalganj", State: "Bihar"},
	{City: "Hajipur", State: "Bihar"},
	{City: "Hilsa", State: "Bihar"},
	{City: "Hisua", State: "Bihar"},
	{City: "Islampur", State: "Bihar"},
	{City: "Jagdispur", State: "Bihar"},
	{City: "Jamalpur", State: "Bihar"},
	{City: "Jamui", State: "Bihar"},
	{City: "Jehanabad", State: "Bihar"},
	{City: "Jhajha", State: "Bihar"},
	{City: "Jhanjharpur", State: "Bihar"},
	{City: "Jogabani", State: "Bihar"},
	{City: "Kanti", State: "Bihar"},
	{City: "Katihar", State: "Bihar"},
	{City: "Khagaria", State: "Bihar"},
	{City: "Kharagpur", State: "Bihar"},
	{City: "Kishanganj", State: "Bihar"},
	{City: "Lakhisarai", State: "Bihar"},
	{City: "Lalganj", State: "Bihar"},
	{City: "Madhepura", State: "Bihar"},
	{City: "Madhubani", State: "Bihar"},
	{City: "Maharajganj", State: "Bihar"},
	{City: "Mahnar Bazar", State: "Bihar"},
	{City: "Makhdumpur", State: "Bihar"},
	{City: "Maner", State: "Bihar"},
	{City: "Manihari", State: "Bihar"},
	{City: "Marhaura", State: "Bihar"},
	{City: "Masaurhi", State: "Bihar"},
	{City: "Mirganj", State: "Bihar"},
	{City: "Mokameh", State: "Bihar"},
	{City: "Motihari", State: "Bihar"},
	{City: "Motipur", State: "Bihar"},
	{City: "Munger", State: "Bihar"},
	{City: "Murliganj", State: "Bihar"},
	{City: "Muzaffarpur", State: "Bihar"},
	{City: "Narkatiaganj", State: "Bihar"},
	{City: "Naugachhia", State: "Bihar"},
	{City: "Nawada", State: "Bihar"},
	{City: "Nokha", State: "Bihar"},
	{City: "Patna", State: "Bihar"},
	{City: "Piro", State: "Bihar"},
	{City: "Purnia", State: "Bihar"},
	{City: "Rafiganj", State: "Bihar"},
	{City: "Rajgir", State: "Bihar"},
	{City: "Ramnagar", State: "Bihar"},
	{City: "Raxaul Bazar", State: "Bihar"},
	{City: "Revelganj", State: "Bihar"},
	{City: "Rosera", State: "Bihar"},
	{City: "Saharsa", State: "Bihar"},
	{City: "Samastipur", State: "Bihar"},
	{City: "Sasaram", State: "Bihar"},
	{City: "Sheikhpura", State: "Bihar"},
	{City: "Sheohar", State: "Bihar"},
	{City: "Sherghati", State: "Bihar"},
	{City: "Silao", State: "Bihar"},
	{City: "Sitamarhi", State: "Bihar"},
	{City: "Siwan", State: "Bihar"},
	{City: "Sonepur", State: "Bihar"},
	{City: "Sugauli", State: "Bihar"},
	{City: "Sultanganj", State: "Bihar"},
	{City: "Supaul", State: "Bihar"},
	{City: "Warisaliganj", State: "Bihar"},
	{City: "Ahiwara", State: "Chhattisgarh"},
	{City: "Akaltara", State: "Chhattisgarh"},
	{City: "Ambagarh Chowki", State: "Chhattisgarh"},
	{City: "Ambikapur", State: "Chhattisgarh"},
	{City: "Arang", State: "Chhattisgarh"},
	{City: "Bade Bacheli", State: "Chhattisgarh"},
	{City: "Balod", State: "Chhattisgarh"},
	{City: "Baloda Bazar", State: "Chhattisgarh"},
	{City: "Bemetra", State: "Chhattisgarh"},
	{City: "Bhatapara", State: "Chhattisgarh"},
	{City: "Bilaspur", State: "Chhattisgarh"},
	{City: "Birgaon", State: "Chhattisgarh"},
	{City: "Champa", State: "Chhattisgarh"},
	{City: "Chirmiri", State: "Chhattisgarh"},
	{City: "Dalli-Rajhara", State: "Chhattisgarh"},
	{City: "Dhamtari", State: "Chhattisgarh"},
	{City: "Dipka", State: "Chhattisgarh"},
	{City: "Dongargarh", State: "Chhattisgarh"},
	{City: "Durg-Bhilai Nagar", State: "Chhattisgarh"},
	{City: "Gobranawapara", State: "Chhattisgarh"},
	{City: "Jagdalpur", State: "Chhattisgarh"},
	{City: "Janjgir", State: "Chhattisgarh"},
	{City: "Jashpurnagar", State: "Chhattisgarh"},
	{City: "Kanker", State: "Chhattisgarh"},
	{City: "Kawardha", State: "Chhattisgarh"},
	{City: "Kondagaon", State: "Chhattisgarh"},
	{City: "Korba", State: "Chhattisgarh"},
	{City: "Mahasamund", State: "Chhattisgarh"},
	{City: "Mahendragarh", State: "Chhattisgarh"},
	{City: "Mungeli", State: "Chhattisgarh"},
	{City: "Naila Janjgir", State: "Chhattisgarh"},
	{City: "Raigarh", State: "Chhattisgarh"},
	{City: "Raipur", State: "Chhattisgarh"},
	{City: "Rajnandgaon", State: "Chhattisgarh"},
	{City: "Sakti", State: "Chhattisgarh"},
	{City: "Tilda Newra", State: "Chhattisgarh"},
	{City: "Amli", State: "Dadra & Nagar Haveli"},
	{City: "Silvassa", State: "Dadra & Nagar Haveli"},
	{City: "Daman and Diu", State: "Daman & Diu"},
	{City: "Daman and Diu", State: "Daman & Diu"},
	{City: "Asola", State: "Delhi"},
	{City: "Delhi", State: "Delhi"},
	{City: "Aldona", State: "Goa"},
	{City: "Curchorem Cacora", State: "Goa"},
	{City: "Madgaon", State: "Goa"},
	{City: "Mapusa", State: "Goa"},
	{City: "Margao", State: "Goa"},
	{City: "Marmagao", State: "Goa"},
	{City: "Panaji", State: "Goa"},
	{City: "Ahmedabad", State: "Gujarat"},
	{City: "Amreli", State: "Gujarat"},
	{City: "Anand", State: "Gujarat"},
	{City: "Ankleshwar", State: "Gujarat"},
	{City: "Bharuch", State: "Gujarat"},
	{City: "Bhavnagar", State: "Gujarat"},
	{City: "Bhuj", State: "Gujarat"},
	{City: "Cambay", State: "Gujarat"},
	{City: "Dahod", State: "Gujarat"},
	{City: "Deesa", State: "Gujarat"},
	{City: "Dharampur", State: " India"},
	{City: "Dholka", State: "Gujarat"},
	{City: "Gandhinagar", State: "Gujarat"},
	{City: "Godhra", State: "Gujarat"},
	{City: "Himatnagar", State: "Gujarat"},
	{City: "Idar", State: "Gujarat"},
	{City: "Jamnagar", State: "Gujarat"},
	{City: "Junagadh", State: "Gujarat"},
	{City: "Kadi", State: "Gujarat"},
	{City: "Kalavad", State: "Gujarat"},
	{City: "Kalol", State: "Gujarat"},
	{City: "Kapadvanj", State: "Gujarat"},
	{City: "Karjan", State: "Gujarat"},
	{City: "Keshod", State: "Gujarat"},
	{City: "Khambhalia", State: "Gujarat"},
	{City: "Khambhat", State: "Gujarat"},
	{City: "Kheda", State: "Gujarat"},
	{City: "Khedbrahma", State: "Gujarat"},
	{City: "Kheralu", State: "Gujarat"},
	{City: "Kodinar", State: "Gujarat"},
	{City: "Lathi", State: "Gujarat"},
	{City: "Limbdi", State: "Gujarat"},
	{City: "Lunawada", State: "Gujarat"},
	{City: "Mahesana", State: "Gujarat"},
	{City: "Mahuva", State: "Gujarat"},
	{City: "Manavadar", State: "Gujarat"},
	{City: "Mandvi", State: "Gujarat"},
	{City: "Mangrol", State: "Gujarat"},
	{City: "Mansa", State: "Gujarat"},
	{City: "Mehmedabad", State: "Gujarat"},
	{City: "Modasa", State: "Gujarat"},
	{City: "Morvi", State: "Gujarat"},
	{City: "Nadiad", State: "Gujarat"},
	{City: "Navsari", State: "Gujarat"},
	{City: "Padra", State: "Gujarat"},
	{City: "Palanpur", State: "Gujarat"},
	{City: "Palitana", State: "Gujarat"},
	{City: "Pardi", State: "Gujarat"},
	{City: "Patan", State: "Gujarat"},
	{City: "Petlad", State: "Gujarat"},
	{City: "Porbandar", State: "Gujarat"},
	{City: "Radhanpur", State: "Gujarat"},
	{City: "Rajkot", State: "Gujarat"},
	{City: "Rajpipla", State: "Gujarat"},
	{City: "Rajula", State: "Gujarat"},
	{City: "Ranavav", State: "Gujarat"},
	{City: "Rapar", State: "Gujarat"},
	{City: "Salaya", State: "Gujarat"},
	{City: "Sanand", State: "Gujarat"},
	{City: "Savarkundla", State: "Gujarat"},
	{City: "Sidhpur", State: "Gujarat"},
	{City: "Sihor", State: "Gujarat"},
	{City: "Songadh", State: "Gujarat"},
	{City: "Surat", State: "Gujarat"},
	{City: "Talaja", State: "Gujarat"},
	{City: "Thangadh", State: "Gujarat"},
	{City: "Tharad", State: "Gujarat"},
	{City: "Umbergaon", State: "Gujarat"},
	{City: "Umreth", State: "Gujarat"},
	{City: "Una", State: "Gujarat"},
	{City: "Unjha", State: "Gujarat"},
	{City: "Upleta", State: "Gujarat"},
	{City: "Vadnagar", State: "Gujarat"},
	{City: "Vadodara", State: "Gujarat"},
	{City: "Valsad", State: "Gujarat"},
	{City: "Vapi", State: "Gujarat"},
	{City: "Vapi", State: "Gujarat"},
	{City: "Veraval", State: "Gujarat"},
	{City: "Vijapur", State: "Gujarat"},
	{City: "Viramgam", State: "Gujarat"},
	{City: "Visnagar", State: "Gujarat"},
	{City: "Vyara", State: "Gujarat"},
	{City: "Wadhwan", State: "Gujarat"},
	{City: "Wankaner", State: "Gujarat"},
	{City: "Adalaj", State: "Gujrat"},
	{City: "Adityana", State: "Gujrat"},
	{City: "Alang", State: "Gujrat"},
	{City: "Ambaji", State: "Gujrat"},
	{City: "Ambaliyasan", State: "Gujrat"},
	{City: "Andada", State: "Gujrat"},
	{City: "Anjar", State: "Gujrat"},
	{City: "Anklav", State: "Gujrat"},
	{City: "Antaliya", State: "Gujrat"},
	{City: "Arambhada", State: "Gujrat"},
	{City: "Atul", State: "Gujrat"},
	{City: "Ballabhgarh", State: "Hariyana"},
	{City: "Ambala", State: "Haryana"},
	{City: "Ambala", State: "Haryana"},
	{City: "Asankhurd", State: "Haryana"},
	{City: "Assandh", State: "Haryana"},
	{City: "Ateli", State: "Haryana"},
	{City: "Babiyal", State: "Haryana"},
	{City: "Bahadurgarh", State: "Haryana"},
	{City: "Barwala", State: "Haryana"},
	{City: "Bhiwani", State: "Haryana"},
	{City: "Charkhi Dadri", State: "Haryana"},
	{City: "Cheeka", State: "Haryana"},
	{City: "Ellenabad 2", State: "Haryana"},
	{City: "Faridabad", State: "Haryana"},
	{City: "Fatehabad", State: "Haryana"},
	{City: "Ganaur", State: "Haryana"},
	{City: "Gharaunda", State: "Haryana"},
	{City: "Gohana", State: "Haryana"},
	{City: "Gurgaon", State: "Haryana"},
	{City: "Haibat(Yamuna Nagar)", State: "Haryana"},
	{City: "Hansi", State: "Haryana"},
	{City: "Hisar", State: "Haryana"},
	{City: "Hodal", State: "Haryana"},
	{City: "Jhajjar", State: "Haryana"},
	{City: "Jind", State: "Haryana"},
	{City: "Kaithal", State: "Haryana"},
	{City: "Kalan Wali", State: "Haryana"},
	{City: "Kalka", State: "Haryana"},
	{City: "Karnal", State: "Haryana"},
	{City: "Ladwa", State: "Haryana"},
	{City: "Mahendragarh", State: "Haryana"},
	{City: "Mandi Dabwali", State: "Haryana"},
	{City: "Narnaul", State: "Haryana"},
	{City: "Narwana", State: "Haryana"},
	{City: "Palwal", State: "Haryana"},
	{City: "Panchkula", State: "Haryana"},
	{City: "Panipat", State: "Haryana"},
	{City: "Pehowa", State: "Haryana"},
	{City: "Pinjore", State: "Haryana"},
	{City: "Rania", State: "Haryana"},
	{City: "Ratia", State: "Haryana"},
	{City: "Rewari", State: "Haryana"},
	{City: "Rohtak", State: "Haryana"},
	{City: "Safidon", State: "Haryana"},
	{City: "Samalkha", State: "Haryana"},
	{City: "Shahbad", State: "Haryana"},
	{City: "Sirsa", State: "Haryana"},
	{City: "Sohna", State: "Haryana"},
	{City: "Sonipat", State: "Haryana"},
	{City: "Taraori", State: "Haryana"},
	{City: "Thanesar", State: "Haryana"},
	{City: "Tohana", State: "Haryana"},
	{City: "Yamunanagar", State: "Haryana"},
	{City: "Arki", State: "Himachal Pradesh"},
	{City: "Baddi", State: "Himachal Pradesh"},
	{City: "Bilaspur", State: "Himachal Pradesh"},
	{City: "Chamba", State: "Himachal Pradesh"},
	{City: "Dalhousie", State: "Himachal Pradesh"},
	{City: "Dharamsala", State: "Himachal Pradesh"},
	{City: "Hamirpur", State: "Himachal Pradesh"},
	{City: "Mandi", State: "Himachal Pradesh"},
	{City: "Nahan", State: "Himachal Pradesh"},
	{City: "Shimla", State: "Himachal Pradesh"},
	{City: "Solan", State: "Himachal Pradesh"},
	{City: "Sundarnagar", State: "Himachal Pradesh"},
	{City: "Jammu", State: "Jammu & Kashmir"},
	{City: "Achabbal", State: "Jammu & Kashmir"},
	{City: "Akhnoor", State: "Jammu & Kashmir"},
	{City: "Anantnag", State: "Jammu & Kashmir"},
	{City: "Arnia", State: "Jammu & Kashmir"},
	{City: "Awantipora", State: "Jammu & Kashmir"},
	{City: "Bandipore", State: "Jammu & Kashmir"},
	{City: "Baramula", State: "Jammu & Kashmir"},
	{City: "Kathua", State: "Jammu & Kashmir"},
	{City: "Leh", State: "Jammu & Kashmir"},
	{City: "Punch", State: "Jammu & Kashmir"},
	{City: "Rajauri", State: "Jammu & Kashmir"},
	{City: "Sopore", State: "Jammu & Kashmir"},
	{City: "Srinagar", State: "Jammu & Kashmir"},
	{City: "Udhampur", State: "Jammu & Kashmir"},
	{City: "Amlabad", State: "Jharkhand"},
	{City: "Ara", State: "Jharkhand"},
	{City: "Barughutu", State: "Jharkhand"},
	{City: "Bokaro Steel City", State: "Jharkhand"},
	{City: "Chaibasa", State: "Jharkhand"},
	{City: "Chakradharpur", State: "Jharkhand"},
	{City: "Chandrapura", State: "Jharkhand"},
	{City: "Chatra", State: "Jharkhand"},
	{City: "Chirkunda", State: "Jharkhand"},
	{City: "Churi", State: "Jharkhand"},
	{City: "Daltonganj", State: "Jharkhand"},
	{City: "Deoghar", State: "Jharkhand"},
	{City: "Dhanbad", State: "Jharkhand"},
	{City: "Dumka", State: "Jharkhand"},
	{City: "Garhwa", State: "Jharkhand"},
	{City: "Ghatshila", State: "Jharkhand"},
	{City: "Giridih", State: "Jharkhand"},
	{City: "Godda", State: "Jharkhand"},
	{City: "Gomoh", State: "Jharkhand"},
	{City: "Gumia", State: "Jharkhand"},
	{City: "Gumla", State: "Jharkhand"},
	{City: "Hazaribag", State: "Jharkhand"},
	{City: "Hussainabad", State: "Jharkhand"},
	{City: "Jamshedpur", State: "Jharkhand"},
	{City: "Jamtara", State: "Jharkhand"},
	{City: "Jhumri Tilaiya", State: "Jharkhand"},
	{City: "Khunti", State: "Jharkhand"},
	{City: "Lohardaga", State: "Jharkhand"},
	{City: "Madhupur", State: "Jharkhand"},
	{City: "Mihijam", State: "Jharkhand"},
	{City: "Musabani", State: "Jharkhand"},
	{City: "Pakaur", State: "Jharkhand"},
	{City: "Patratu", State: "Jharkhand"},
	{City: "Phusro", State: "Jharkhand"},
	{City: "Ramngarh", State: "Jharkhand"},
	{City: "Ranchi", State: "Jharkhand"},
	{City: "Sahibganj", State: "Jharkhand"},
	{City: "Saunda", State: "Jharkhand"},
	{City: "Simdega", State: "Jharkhand"},
	{City: "Tenu Dam-cum- Kathhara", State: "Jharkhand"},
	{City: "Arasikere", State: "Karnataka"},
	{City: "Bangalore", State: "Karnataka"},
	{City: "Belgaum", State: "Karnataka"},
	{City: "Bellary", State: "Karnataka"},
	{City: "Chamrajnagar", State: "Karnataka"},
	{City: "Chikkaballapur", State: "Karnataka"},
	{City: "Chintamani", State: "Karnataka"},
	{City: "Chitradurga", State: "Karnataka"},
	{City: "Gulbarga", State: "Karnataka"},
	{City: "Gundlupet", State: "Karnataka"},
	{City: "Hassan", State: "Karnataka"},
	{City: "Hospet", State: "Karnataka"},
	{City: "Hubli", State: "Karnataka"},
	{City: "Karkala", State: "Karnataka"},
	{City: "Karwar", State: "Karnataka"},
	{City: "Kolar", State: "Karnataka"},
	{City: "Kota", State: "Karnataka"},
	{City: "Lakshmeshwar", State: "Karnataka"},
	{City: "Lingsugur", State: "Karnataka"},
	{City: "Maddur", State: "Karnataka"},
	{City: "Madhugiri", State: "Karnataka"},
	{City: "Madikeri", State: "Karnataka"},
	{City: "Magadi", State: "Karnataka"},
	{City: "Mahalingpur", State: "Karnataka"},
	{City: "Malavalli", State: "Karnataka"},
	{City: "Malur", State: "Karnataka"},
	{City: "Mandya", State: "Karnataka"},
	{City: "Mangalore", State: "Karnataka"},
	{City: "Manvi", State: "Karnataka"},
	{City: "Mudalgi", State: "Karnataka"},
	{City: "Mudbidri", State: "Karnataka"},
	{City: "Muddebihal", State: "Karnataka"},
	{City: "Mudhol", State: "Karnataka"},
	{City: "Mulbagal", State: "Karnataka"},
	{City: "Mundargi", State: "Karnataka"},
	{City: "Mysore", State: "Karnataka"},
	{City: "Nanjangud", State: "Karnataka"},
	{City: "Pavagada", State: "Karnataka"},
	{City: "Puttur", State: "Karnataka"},
	{City: "Rabkavi Banhatti", State: "Karnataka"},
	{City: "Raichur", State: "Karnataka"},
	{City: "Ramanagaram", State: "Karnataka"},
	{City: "Ramdurg", State: "Karnataka"},
	{City: "Ranibennur", State: "Karnataka"},
	{City: "Robertson Pet", State: "Karnataka"},
	{City: "Ron", State: "Karnataka"},
	{City: "Sadalgi", State: "Karnataka"},
	{City: "Sagar", State: "Karnataka"},
	{City: "Sakleshpur", State: "Karnataka"},
	{City: "Sandur", State: "Karnataka"},
	{City: "Sankeshwar", State: "Karnataka"},
	{City: "Saundatti-Yellamma", State: "Karnataka"},
	{City: "Savanur", State: "Karnataka"},
	{City: "Sedam", State: "Karnataka"},
	{City: "Shahabad", State: "Karnataka"},
	{City: "Shahpur", State: "Karnataka"},
	{City: "Shiggaon", State: "Karnataka"},
	{City: "Shikapur", State: "Karnataka"},
	{City: "Shimoga", State: "Karnataka"},
	{City: "Shorapur", State: "Karnataka"},
	{City: "Shrirangapattana", State: "Karnataka"},
	{City: "Sidlaghatta", State: "Karnataka"},
	{City: "Sindgi", State: "Karnataka"},
	{City: "Sindhnur", State: "Karnataka"},
	{City: "Sira", State: "Karnataka"},
	{City: "Sirsi", State: "Karnataka"},
	{City: "Siruguppa", State: "Karnataka"},
	{City: "Srinivaspur", State: "Karnataka"},
	{City: "Talikota", State: "Karnataka"},
	{City: "Tarikere", State: "Karnataka"},
	{City: "Tekkalakota", State: "Karnataka"},
	{City: "Terdal", State: "Karnataka"},
	{City: "Tiptur", State: "Karnataka"},
	{City: "Tumkur", State: "Karnataka"},
	{City: "Udupi", State: "Karnataka"},
	{City: "Vijayapura", State: "Karnataka"},
	{City: "Wadi", State: "Karnataka"},
	{City: "Yadgir", State: "Karnataka"},
	{City: "Adoor", State: "Kerala"},
	{City: "Akathiyoor", State: "Kerala"},
	{City: "Alappuzha", State: "Kerala"},
	{City: "Ancharakandy", State: "Kerala"},
	{City: "Aroor", State: "Kerala"},
	{City: "Ashtamichira", State: "Kerala"},
	{City: "Attingal", State: "Kerala"},
	{City: "Avinissery", State: "Kerala"},
	{City: "Chalakudy", State: "Kerala"},
	{City: "Changanassery", State: "Kerala"},
	{City: "Chendamangalam", State: "Kerala"},
	{City: "Chengannur", State: "Kerala"},
	{City: "Cherthala", State: "Kerala"},
	{City: "Cheruthazham", State: "Kerala"},
	{City: "Chittur-Thathamangalam", State: "Kerala"},
	{City: "Chockli", State: "Kerala"},
	{City: "Erattupetta", State: "Kerala"},
	{City: "Guruvayoor", State: "Kerala"},
	{City: "Irinjalakuda", State: "Kerala"},
	{City: "Kadirur", State: "Kerala"},
	{City: "Kalliasseri", State: "Kerala"},
	{City: "Kalpetta", State: "Kerala"},
	{City: "Kanhangad", State: "Kerala"},
	{City: "Kanjikkuzhi", State: "Kerala"},
	{City: "Kannur", State: "Kerala"},
	{City: "Kasaragod", State: "Kerala"},
	{City: "Kayamkulam", State: "Kerala"},
	{City: "Kochi", State: "Kerala"},
	{City: "Kodungallur", State: "Kerala"},
	{City: "Kollam", State: "Kerala"},
	{City: "Koothuparamba", State: "Kerala"},
	{City: "Kothamangalam", State: "Kerala"},
	{City: "Kottayam", State: "Kerala"},
	{City: "Kozhikode", State: "Kerala"},
	{City: "Kunnamkulam", State: "Kerala"},
	{City: "Malappuram", State: "Kerala"},
	{City: "Mattannur", State: "Kerala"},
	{City: "Mavelikkara", State: "Kerala"},
	{City: "Mavoor", State: "Kerala"},
	{City: "Muvattupuzha", State: "Kerala"},
	{City: "Nedumangad", State: "Kerala"},
	{City: "Neyyattinkara", State: "Kerala"},
	{City: "Ottappalam", State: "Kerala"},
	{City: "Palai", State: "Kerala"},
	{City: "Palakkad", State: "Kerala"},
	{City: "Panniyannur", State: "Kerala"},
	{City: "Pappinisseri", State: "Kerala"},
	{City: "Paravoor", State: "Kerala"},
	{City: "Pathanamthitta", State: "Kerala"},
	{City: "Payyannur", State: "Kerala"},
	{City: "Peringathur", State: "Kerala"},
	{City: "Perinthalmanna", State: "Kerala"},
	{City: "Perumbavoor", State: "Kerala"},
	{City: "Ponnani", State: "Kerala"},
	{City: "Punalur", State: "Kerala"},
	{City: "Quilandy", State: "Kerala"},
	{City: "Shoranur", State: "Kerala"},
	{City: "Taliparamba", State: "Kerala"},
	{City: "Thiruvalla", State: "Kerala"},
	{City: "Thiruvananthapuram", State: "Kerala"},
	{City: "Thodupuzha", State: "Kerala"},
	{City: "Thrissur", State: "Kerala"},
	{City: "Tirur", State: "Kerala"},
	{City: "Vadakara", State: "Kerala"},
	{City: "Vaikom", State: "Kerala"},
	{City: "Varkala", State: "Kerala"},
	{City: "Kavaratti", State: "Lakshadweep"},
	{City: "Ashok Nagar", State: "Madhya Pradesh"},
	{City: "Balaghat", State: "Madhya Pradesh"},
	{City: "Betul", State: "Madhya Pradesh"},
	{City: "Bhopal", State: "Madhya Pradesh"},
	{City: "Burhanpur", State: "Madhya Pradesh"},
	{City: "Chhatarpur", State: "Madhya Pradesh"},
	{City: "Dabra", State: "Madhya Pradesh"},
	{City: "Datia", State: "Madhya Pradesh"},
	{City: "Dewas", State: "Madhya Pradesh"},
	{City: "Dhar", State: "Madhya Pradesh"},
	{City: "Fatehabad", State: "Madhya Pradesh"},
	{City: "Gwalior", State: "Madhya Pradesh"},
	{City: "Indore", State: "Madhya Pradesh"},
	{City: "Itarsi", State: "Madhya Pradesh"},
	{City: "Jabalpur", State: "Madhya Pradesh"},
	{City: "Katni", State: "Madhya Pradesh"},
	{City: "Kotma", State: "Madhya Pradesh"},
	{City: "Lahar", State: "Madhya Pradesh"},
	{City: "Lundi", State: "Madhya Pradesh"},
	{City: "Maharajpur", State: "Madhya Pradesh"},
	{City: "Mahidpur", State: "Madhya Pradesh"},
	{City: "Maihar", State: "Madhya Pradesh"},
	{City: "Malajkhand", State: "Madhya Pradesh"},
	{City: "Manasa", State: "Madhya Pradesh"},
	{City: "Manawar", State: "Madhya Pradesh"},
	{City: "Mandideep", State: "Madhya Pradesh"},
	{City: "Mandla", State: "Madhya Pradesh"},
	{City: "Mandsaur", State: "Madhya Pradesh"},
	{City: "Mauganj", State: "Madhya Pradesh"},
	{City: "Mhow Cantonment", State: "Madhya Pradesh"},
	{City: "Mhowgaon", State: "Madhya Pradesh"},
	{City: "Morena", State: "Madhya Pradesh"},
	{City: "Multai", State: "Madhya Pradesh"},
	{City: "Murwara", State: "Madhya Pradesh"},
	{City: "Nagda", State: "Madhya Pradesh"},
	{City: "Nainpur", State: "Madhya Pradesh"},
	{City: "Narsinghgarh", State: "Madhya Pradesh"},
	{City: "Narsinghgarh", State: "Madhya Pradesh"},
	{City: "Neemuch", State: "Madhya Pradesh"},
	{City: "Nepanagar", State: "Madhya Pradesh"},
	{City: "Niwari", State: "Madhya Pradesh"},
	{City: "Nowgong", State: "Madhya Pradesh"},
	{City: "Nowrozabad", State: "Madhya Pradesh"},
	{City: "Pachore", State: "Madhya Pradesh"},
	{City: "Pali", State: "Madhya Pradesh"},
	{City: "Panagar", State: "Madhya Pradesh"},
	{City: "Pandhurna", State: "Madhya Pradesh"},
	{City: "Panna", State: "Madhya Pradesh"},
	{City: "Pasan", State: "Madhya Pradesh"},
	{City: "Pipariya", State: "Madhya Pradesh"},
	{City: "Pithampur", State: "Madhya Pradesh"},
	{City: "Porsa", State: "Madhya Pradesh"},
	{City: "Prithvipur", State: "Madhya Pradesh"},
	{City: "Raghogarh-Vijaypur", State: "Madhya Pradesh"},
	{City: "Rahatgarh", State: "Madhya Pradesh"},
	{City: "Raisen", State: "Madhya Pradesh"},
	{City: "Rajgarh", State: "Madhya Pradesh"},
	{City: "Ratlam", State: "Madhya Pradesh"},
	{City: "Rau", State: "Madhya Pradesh"},
	{City: "Rehli", State: "Madhya Pradesh"},
	{City: "Rewa", State: "Madhya Pradesh"},
	{City: "Sabalgarh", State: "Madhya Pradesh"},
	{City: "Sagar", State: "Madhya Pradesh"},
	{City: "Sanawad", State: "Madhya Pradesh"},
	{City: "Sarangpur", State: "Madhya Pradesh"},
	{City: "Sarni", State: "Madhya Pradesh"},
	{City: "Satna", State: "Madhya Pradesh"},
	{City: "Sausar", State: "Madhya Pradesh"},
	{City: "Sehore", State: "Madhya Pradesh"},
	{City: "Sendhwa", State: "Madhya Pradesh"},
	{City: "Seoni", State: "Madhya Pradesh"},
	{City: "Seoni-Malwa", State: "Madhya Pradesh"},
	{City: "Shahdol", State: "Madhya Pradesh"},
	{City: "Shajapur", State: "Madhya Pradesh"},
	{City: "Shamgarh", State: "Madhya Pradesh"},
	{City: "Sheopur", State: "Madhya Pradesh"},
	{City: "Shivpuri", State: "Madhya Pradesh"},
	{City: "Shujalpur", State: "Madhya Pradesh"},
	{City: "Sidhi", State: "Madhya Pradesh"},
	{City: "Sihora", State: "Madhya Pradesh"},
	{City: "Singrauli", State: "Madhya Pradesh"},
	{City: "Sironj", State: "Madhya Pradesh"},
	{City: "Sohagpur", State: "Madhya Pradesh"},
	{City: "Tarana", State: "Madhya Pradesh"},
	{City: "Tikamgarh", State: "Madhya Pradesh"},
	{City: "Ujhani", State: "Madhya Pradesh"},
	{City: "Ujjain", State: "Madhya Pradesh"},
	{City: "Umaria", State: "Madhya Pradesh"},
	{City: "Vidisha", State: "Madhya Pradesh"},
	{City: "Wara Seoni", State: "Madhya Pradesh"},
	{City: "Ahmednagar", State: "Maharashtra"},
	{City: "Akola", State: "Maharashtra"},
	{City: "Amravati", State: "Maharashtra"},
	{City: "Aurangabad", State: "Maharashtra"},
	{City: "Baramati", State: "Maharashtra"},
	{City: "Chalisgaon", State: "Maharashtra"},
	{City: "Chinchani", State: "Maharashtra"},
	{City: "Devgarh", State: "Maharashtra"},
	{City: "Dhule", State: "Maharashtra"},
	{City: "Dombivli", State: "Maharashtra"},
	{City: "Durgapur", State: "Maharashtra"},
	{City: "Ichalkaranji", State: "Maharashtra"},
	{City: "Jalna", State: "Maharashtra"},
	{City: "Kalyan", State: "Maharashtra"},
	{City: "Latur", State: "Maharashtra"},
	{City: "Loha", State: "Maharashtra"},
	{City: "Lonar", State: "Maharashtra"},
	{City: "Lonavla", State: "Maharashtra"},
	{City: "Mahad", State: "Maharashtra"},
	{City: "Mahuli", State: "Maharashtra"},
	{City: "Malegaon", State: "Maharashtra"},
	{City: "Malkapur", State: "Maharashtra"},
	{City: "Manchar", State: "Maharashtra"},
	{City: "Mangalvedhe", State: "Maharashtra"},
	{City: "Mangrulpir", State: "Maharashtra"},
	{City: "Manjlegaon", State: "Maharashtra"},
	{City: "Manmad", State: "Maharashtra"},
	{City: "Manwath", State: "Maharashtra"},
	{City: "Mehkar", State: "Maharashtra"},
	{City: "Mhaswad", State: "Maharashtra"},
	{City: "Miraj", State: "Maharashtra"},
	{City: "Morshi", State: "Maharashtra"},
	{City: "Mukhed", State: "Maharashtra"},
	{City: "Mul", State: "Maharashtra"},
	{City: "Mumbai", State: "Maharashtra"},
	{City: "Murtijapur", State: "Maharashtra"},
	{City: "Nagpur", State: "Maharashtra"},
	{City: "Nalasopara", State: "Maharashtra"},
	{City: "Nanded-Waghala", State: "Maharashtra"},
	{City: "Nandgaon", State: "Maharashtra"},
	{City: "Nandura", State: "Maharashtra"},
	{City: "Nandurbar", State: "Maharashtra"},
	{City: "Narkhed", State: "Maharashtra"},
	{City: "Nashik", State: "Maharashtra"},
	{City: "Navi Mumbai", State: "Maharashtra"},
	{City: "Nawapur", State: "Maharashtra"},
	{City: "Nilanga", State: "Maharashtra"},
	{City: "Osmanabad", State: "Maharashtra"},
	{City: "Ozar", State: "Maharashtra"},
	{City: "Pachora", State: "Maharashtra"},
	{City: "Paithan", State: "Maharashtra"},
	{City: "Palghar", State: "Maharashtra"},
	{City: "Pandharkaoda", State: "Maharashtra"},
	{City: "Pandharpur", State: "Maharashtra"},
	{City: "Panvel", State: "Maharashtra"},
	{City: "Parbhani", State: "Maharashtra"},
	{City: "Parli", State: "Maharashtra"},
	{City: "Parola", State: "Maharashtra"},
	{City: "Partur", State: "Maharashtra"},
	{City: "Pathardi", State: "Maharashtra"},
	{City: "Pathri", State: "Maharashtra"},
	{City: "Patur", State: "Maharashtra"},
	{City: "Pauni", State: "Maharashtra"},
	{City: "Pen", State: "Maharashtra"},
	{City: "Phaltan", State: "Maharashtra"},
	{City: "Pulgaon", State: "Maharashtra"},
	{City: "Pune", State: "Maharashtra"},
	{City: "Purna", State: "Maharashtra"},
	{City: "Pusad", State: "Maharashtra"},
	{City: "Rahuri", State: "Maharashtra"},
	{City: "Rajura", State: "Maharashtra"},
	{City: "Ramtek", State: "Maharashtra"},
	{City: "Ratnagiri", State: "Maharashtra"},
	{City: "Raver", State: "Maharashtra"},
	{City: "Risod", State: "Maharashtra"},
	{City: "Sailu", State: "Maharashtra"},
	{City: "Sangamner", State: "Maharashtra"},
	{City: "Sangli", State: "Maharashtra"},
	{City: "Sangole", State: "Maharashtra"},
	{City: "Sasvad", State: "Maharashtra"},
	{City: "Satana", State: "Maharashtra"},
	{City: "Satara", State: "Maharashtra"},
	{City: "Savner", State: "Maharashtra"},
	{City: "Sawantwadi", State: "Maharashtra"},
	{City: "Shahade", State: "Maharashtra"},
	{City: "Shegaon", State: "Maharashtra"},
	{City: "Shendurjana", State: "Maharashtra"},
	{City: "Shirdi", State: "Maharashtra"},
	{City: "Shirpur-Warwade", State: "Maharashtra"},
	{City: "Shirur", State: "Maharashtra"},
	{City: "Shrigonda", State: "Maharashtra"},
	{City: "Shrirampur", State: "Maharashtra"},
	{City: "Sillod", State: "Maharashtra"},
	{City: "Sinnar", State: "Maharashtra"},
	{City: "Solapur", State: "Maharashtra"},
	{City: "Soyagaon", State: "Maharashtra"},
	{City: "Talegaon Dabhade", State: "Maharashtra"},
	{City: "Talode", State: "Maharashtra"},
	{City: "Tasgaon", State: "Maharashtra"},
	{City: "Tirora", State: "Maharashtra"},
	{City: "Tuljapur", State: "Maharashtra"},
	{City: "Tumsar", State: "Maharashtra"},
	{City: "Uran", State: "Maharashtra"},
	{City: "Uran Islampur", State: "Maharashtra"},
	{City: "Wadgaon Road", State: "Maharashtra"},
	{City: "Wai", State: "Maharashtra"},
	{City: "Wani", State: "Maharashtra"},
	{City: "Wardha", State: "Maharashtra"},
	{City: "Warora", State: "Maharashtra"},
	{City: "Warud", State: "Maharashtra"},
	{City: "Washim", State: "Maharashtra"},
	{City: "Yevla", State: "Maharashtra"},
	{City: "Uchgaon", State: "Maharashtra"},
	{City: "Udgir", State: "Maharashtra"},
	{City: "Umarga", State: "Maharastra"},
	{City: "Umarkhed", State: "Maharastra"},
	{City: "Umred", State: "Maharastra"},
	{City: "Vadgaon Kasba", State: "Maharastra"},
	{City: "Vaijapur", State: "Maharastra"},
	{City: "Vasai", State: "Maharastra"},
	{City: "Virar", State: "Maharastra"},
	{City: "Vita", State: "Maharastra"},
	{City: "Yavatmal", State: "Maharastra"},
	{City: "Yawal", State: "Maharastra"},
	{City: "Imphal", State: "Manipur"},
	{City: "Kakching", State: "Manipur"},
	{City: "Lilong", State: "Manipur"},
	{City: "Mayang Imphal", State: "Manipur"},
	{City: "Thoubal", State: "Manipur"},
	{City: "Jowai", State: "Meghalaya"},
	{City: "Nongstoin", State: "Meghalaya"},
	{City: "Shillong", State: "Meghalaya"},
	{City: "Tura", State: "Meghalaya"},
	{City: "Aizawl", State: "Mizoram"},
	{City: "Champhai", State: "Mizoram"},
	{City: "Lunglei", State: "Mizoram"},
	{City: "Saiha", State: "Mizoram"},
	{City: "Dimapur", State: "Nagaland"},
	{City: "Kohima", State: "Nagaland"},
	{City: "Mokokchung", State: "Nagaland"},
	{City: "Tuensang", State: "Nagaland"},
	{City: "Wokha", State: "Nagaland"},
	{City: "Zunheboto", State: "Nagaland"},
	{City: "Anandapur", State: "Orissa"},
	{City: "Anugul", State: "Orissa"},
	{City: "Asika", State: "Orissa"},
	{City: "Balangir", State: "Orissa"},
	{City: "Balasore", State: "Orissa"},
	{City: "Baleshwar", State: "Orissa"},
	{City: "Bamra", State: "Orissa"},
	{City: "Barbil", State: "Orissa"},
	{City: "Bargarh", State: "Orissa"},
	{City: "Bargarh", State: "Orissa"},
	{City: "Baripada", State: "Orissa"},
	{City: "Basudebpur", State: "Orissa"},
	{City: "Belpahar", State: "Orissa"},
	{City: "Bhadrak", State: "Orissa"},
	{City: "Bhawanipatna", State: "Orissa"},
	{City: "Bhuban", State: "Orissa"},
	{City: "Bhubaneswar", State: "Orissa"},
	{City: "Biramitrapur", State: "Orissa"},
	{City: "Brahmapur", State: "Orissa"},
	{City: "Brajrajnagar", State: "Orissa"},
	{City: "Byasanagar", State: "Orissa"},
	{City: "Cuttack", State: "Orissa"},
	{City: "Debagarh", State: "Orissa"},
	{City: "Dhenkanal", State: "Orissa"},
	{City: "Gunupur", State: "Orissa"},
	{City: "Hinjilicut", State: "Orissa"},
	{City: "Jagatsinghapur", State: "Orissa"},
	{City: "Jajapur", State: "Orissa"},
	{City: "Jaleswar", State: "Orissa"},
	{City: "Jatani", State: "Orissa"},
	{City: "Jeypur", State: "Orissa"},
	{City: "Jharsuguda", State: "Orissa"},
	{City: "Joda", State: "Orissa"},
	{City: "Kantabanji", State: "Orissa"},
	{City: "Karanjia", State: "Orissa"},
	{City: "Kendrapara", State: "Orissa"},
	{City: "Kendujhar", State: "Orissa"},
	{City: "Khordha", State: "Orissa"},
	{City: "Koraput", State: "Orissa"},
	{City: "Malkangiri", State: "Orissa"},
	{City: "Nabarangapur", State: "Orissa"},
	{City: "Paradip", State: "Orissa"},
	{City: "Parlakhemundi", State: "Orissa"},
	{City: "Pattamundai", State: "Orissa"},
	{City: "Phulabani", State: "Orissa"},
	{City: "Puri", State: "Orissa"},
	{City: "Rairangpur", State: "Orissa"},
	{City: "Rajagangapur", State: "Orissa"},
	{City: "Raurkela", State: "Orissa"},
	{City: "Rayagada", State: "Orissa"},
	{City: "Sambalpur", State: "Orissa"},
	{City: "Soro", State: "Orissa"},
	{City: "Sunabeda", State: "Orissa"},
	{City: "Sundargarh", State: "Orissa"},
	{City: "Talcher", State: "Orissa"},
	{City: "Titlagarh", State: "Orissa"},
	{City: "Umarkote", State: "Orissa"},
	{City: "Karaikal", State: "Pondicherry"},
	{City: "Mahe", State: "Pondicherry"},
	{City: "Pondicherry", State: "Pondicherry"},
	{City: "Yanam", State: "Pondicherry"},
	{City: "Ahmedgarh", State: "Punjab"},
	{City: "Amritsar", State: "Punjab"},
	{City: "Barnala", State: "Punjab"},
	{City: "Batala", State: "Punjab"},
	{City: "Bathinda", State: "Punjab"},
	{City: "Bhagha Purana", State: "Punjab"},
	{City: "Budhlada", State: "Punjab"},
	{City: "Chandigarh", State: "Punjab"},
	{City: "Dasua", State: "Punjab"},
	{City: "Dhuri", State: "Punjab"},
	{City: "Dinanagar", State: "Punjab"},
	{City: "Faridkot", State: "Punjab"},
	{City: "Fazilka", State: "Punjab"},
	{City: "Firozpur", State: "Punjab"},
	{City: "Firozpur Cantt.", State: "Punjab"},
	{City: "Giddarbaha", State: "Punjab"},
	{City: "Gobindgarh", State: "Punjab"},
	{City: "Gurdaspur", State: "Punjab"},
	{City: "Hoshiarpur", State: "Punjab"},
	{City: "Jagraon", State: "Punjab"},
	{City: "Jaitu", State: "Punjab"},
	{City: "Jalalabad", State: "Punjab"},
	{City: "Jalandhar", State: "Punjab"},
	{City: "Jalandhar Cantt.", State: "Punjab"},
	{City: "Jandiala", State: "Punjab"},
	{City: "Kapurthala", State: "Punjab"},
	{City: "Karoran", State: "Punjab"},
	{City: "Kartarpur", State: "Punjab"},
	{City: "Khanna", State: "Punjab"},
	{City: "Kharar", State: "Punjab"},
	{City: "Kot Kapura", State: "Punjab"},
	{City: "Kurali", State: "Punjab"},
	{City: "Longowal", State: "Punjab"},
	{City: "Ludhiana", State: "Punjab"},
	{City: "Malerkotla", State: "Punjab"},
	{City: "Malout", State: "Punjab"},
	{City: "Mansa", State: "Punjab"},
	{City: "Maur", State: "Punjab"},
	{City: "Moga", State: "Punjab"},
	{City: "Mohali", State: "Punjab"},
	{City: "Morinda", State: "Punjab"},
	{City: "Mukerian", State: "Punjab"},
	{City: "Muktsar", State: "Punjab"},
	{City: "Nabha", State: "Punjab"},
	{City: "Nakodar", State: "Punjab"},
	{City: "Nangal", State: "Punjab"},
	{City: "Nawanshahr", State: "Punjab"},
	{City: "Pathankot", State: "Punjab"},
	{City: "Patiala", State: "Punjab"},
	{City: "Patran", State: "Punjab"},
	{City: "Patti", State: "Punjab"},
	{City: "Phagwara", State: "Punjab"},
	{City: "Phillaur", State: "Punjab"},
	{City: "Qadian", State: "Punjab"},
	{City: "Raikot", State: "Punjab"},
	{City: "Rajpura", State: "Punjab"},
	{City: "Rampura Phul", State: "Punjab"},
	{City: "Rupnagar", State: "Punjab"},
	{City: "Samana", State: "Punjab"},
	{City: "Sangrur", State: "Punjab"},
	{City: "Sirhind Fatehgarh Sahib", State: "Punjab"},
	{City: "Sujanpur", State: "Punjab"},
	{City: "Sunam", State: "Punjab"},
	{City: "Talwara", State: "Punjab"},
	{City: "Tarn Taran", State: "Punjab"},
	{City: "Urmar Tanda", State: "Punjab"},
	{City: "Zira", State: "Punjab"},
	{City: "Zirakpur", State: "Punjab"},
	{City: "Bali", State: "Rajasthan"},
	{City: "Banswara", State: "Rajastan"},
	{City: "Ajmer", State: "Rajasthan"},
	{City: "Alwar", State: "Rajasthan"},
	{City: "Bandikui", State: "Rajasthan"},
	{City: "Baran", State: "Rajasthan"},
	{City: "Barmer", State: "Rajasthan"},
	{City: "Bikaner", State: "Rajasthan"},
	{City: "Fatehpur", State: "Rajasthan"},
	{City: "Jaipur", State: "Rajasthan"},
	{City: "Jaisalmer", State: "Rajasthan"},
	{City: "Jodhpur", State: "Rajasthan"},
	{City: "Kota", State: "Rajasthan"},
	{City: "Lachhmangarh", State: "Rajasthan"},
	{City: "Ladnu", State: "Rajasthan"},
	{City: "Lakheri", State: "Rajasthan"},
	{City: "Lalsot", State: "Rajasthan"},
	{City: "Losal", State: "Rajasthan"},
	{City: "Makrana", State: "Rajasthan"},
	{City: "Malpura", State: "Rajasthan"},
	{City: "Mandalgarh", State: "Rajasthan"},
	{City: "Mandawa", State: "Rajasthan"},
	{City: "Mangrol", State: "Rajasthan"},
	{City: "Merta city", State: "Rajasthan"},
	{City: "Mount Abu", State: "Rajasthan"},
	{City: "Nadbai", State: "Rajasthan"},
	{City: "Nagar", State: "Rajasthan"},
	{City: "Nagaur", State: "Rajasthan"},
	{City: "Nargund", State: "Rajasthan"},
	{City: "Nasirabad", State: "Rajasthan"},
	{City: "Nathdwara", State: "Rajasthan"},
	{City: "Navalgund", State: "Rajasthan"},
	{City: "Nawalgarh", State: "Rajasthan"},
	{City: "Neem-Ka-Thana", State: "Rajasthan"},
	{City: "Nelamangala", State: "Rajasthan"},
	{City: "Nimbahera", State: "Rajasthan"},
	{City: "Nipani", State: "Rajasthan"},
	{City: "Niwai", State: "Rajasthan"},
	{City: "Nohar", State: "Rajasthan"},
	{City: "Nokha", State: "Rajasthan"},
	{City: "Pali", State: "Rajasthan"},
	{City: "Phalodi", State: "Rajasthan"},
	{City: "Phulera", State: "Rajasthan"},
	{City: "Pilani", State: "Rajasthan"},
	{City: "Pilibanga", State: "Rajasthan"},
	{City: "Pindwara", State: "Rajasthan"},
	{City: "Pipar city", State: "Rajasthan"},
	{City: "Prantij", State: "Rajasthan"},
	{City: "Pratapgarh", State: "Rajasthan"},
	{City: "Raisinghnagar", State: "Rajasthan"},
	{City: "Rajakhera", State: "Rajasthan"},
	{City: "Rajaldesar", State: "Rajasthan"},
	{City: "Rajgarh (Alwar)", State: "Rajasthan"},
	{City: "Rajgarh (Churu", State: "Rajasthan"},
	{City: "Rajsamand", State: "Rajasthan"},
	{City: "Ramganj Mandi", State: "Rajasthan"},
	{City: "Ramngarh", State: "Rajasthan"},
	{City: "Ratangarh", State: "Rajasthan"},
	{City: "Rawatbhata", State: "Rajasthan"},
	{City: "Rawatsar", State: "Rajasthan"},
	{City: "Reengus", State: "Rajasthan"},
	{City: "Sadri", State: "Rajasthan"},
	{City: "Sadulshahar", State: "Rajasthan"},
	{City: "Sagwara", State: "Rajasthan"},
	{City: "Sambhar", State: "Rajasthan"},
	{City: "Sanchore", State: "Rajasthan"},
	{City: "Sangaria", State: "Rajasthan"},
	{City: "Sardarshahar", State: "Rajasthan"},
	{City: "Sawai Madhopur", State: "Rajasthan"},
	{City: "Shahpura", State: "Rajasthan"},
	{City: "Shahpura", State: "Rajasthan"},
	{City: "Sheoganj", State: "Rajasthan"},
	{City: "Sikar", State: "Rajasthan"},
	{City: "Sirohi", State: "Rajasthan"},
	{City: "Sojat", State: "Rajasthan"},
	{City: "Sri Madhopur", State: "Rajasthan"},
	{City: "Sujangarh", State: "Rajasthan"},
	{City: "Sumerpur", State: "Rajasthan"},
	{City: "Suratgarh", State: "Rajasthan"},
	{City: "Taranagar", State: "Rajasthan"},
	{City: "Todabhim", State: "Rajasthan"},
	{City: "Todaraisingh", State: "Rajasthan"},
	{City: "Tonk", State: "Rajasthan"},
	{City: "Udaipur", State: "Rajasthan"},
	{City: "Udaipurwati", State: "Rajasthan"},
	{City: "Vijainagar", State: "Rajasthan"},
	{City: "Gangtok", State: "Sikkim"},
	{City: "Calcutta", State: "West Bengal"},
	{City: "Arakkonam", State: "Tamil Nadu"},
	{City: "Arcot", State: "Tamil Nadu"},
	{City: "Aruppukkottai", State: "Tamil Nadu"},
	{City: "Bhavani", State: "Tamil Nadu"},
	{City: "Chengalpattu", State: "Tamil Nadu"},
	{City: "Chennai", State: "Tamil Nadu"},
	{City: "Chinna salem", State: "Tamil nadu"},
	{City: "Coimbatore", State: "Tamil Nadu"},
	{City: "Coonoor", State: "Tamil Nadu"},
	{City: "Cuddalore", State: "Tamil Nadu"},
	{City: "Dharmapuri", State: "Tamil Nadu"},
	{City: "Dindigul", State: "Tamil Nadu"},
	{City: "Erode", State: "Tamil Nadu"},
	{City: "Gudalur", State: "Tamil Nadu"},
	{City: "Gudalur", State: "Tamil Nadu"},
	{City: "Gudalur", State: "Tamil Nadu"},
	{City: "Kanchipuram", State: "Tamil Nadu"},
	{City: "Karaikudi", State: "Tamil Nadu"},
	{City: "Karungal", State: "Tamil Nadu"},
	{City: "Karur", State: "Tamil Nadu"},
	{City: "Kollankodu", State: "Tamil Nadu"},
	{City: "Lalgudi", State: "Tamil Nadu"},
	{City: "Madurai", State: "Tamil Nadu"},
	{City: "Nagapattinam", State: "Tamil Nadu"},
	{City: "Nagercoil", State: "Tamil Nadu"},
	{City: "Namagiripettai", State: "Tamil Nadu"},
	{City: "Namakkal", State: "Tamil Nadu"},
	{City: "Nandivaram-Guduvancheri", State: "Tamil Nadu"},
	{City: "Nanjikottai", State: "Tamil Nadu"},
	{City: "Natham", State: "Tamil Nadu"},
	{City: "Nellikuppam", State: "Tamil Nadu"},
	{City: "Neyveli", State: "Tamil Nadu"},
	{City: "O Valley", State: "Tamil Nadu"},
	{City: "Oddanchatram", State: "Tamil Nadu"},
	{City: "P.N.Patti", State: "Tamil Nadu"},
	{City: "Pacode", State: "Tamil Nadu"},
	{City: "Padmanabhapuram", State: "Tamil Nadu"},
	{City: "Palani", State: "Tamil Nadu"},
	{City: "Palladam", State: "Tamil Nadu"},
	{City: "Pallapatti", State: "Tamil Nadu"},
	{City: "Pallikonda", State: "Tamil Nadu"},
	{City: "Panagudi", State: "Tamil Nadu"},
	{City: "Panruti", State: "Tamil Nadu"},
	{City: "Paramakudi", State: "Tamil Nadu"},
	{City: "Parangipettai", State: "Tamil Nadu"},
	{City: "Pattukkottai", State: "Tamil Nadu"},
	{City: "Perambalur", State: "Tamil Nadu"},
	{City: "Peravurani", State: "Tamil Nadu"},
	{City: "Periyakulam", State: "Tamil Nadu"},
	{City: "Periyasemur", State: "Tamil Nadu"},
	{City: "Pernampattu", State: "Tamil Nadu"},
	{City: "Pollachi", State: "Tamil Nadu"},
	{City: "Polur", State: "Tamil Nadu"},
	{City: "Ponneri", State: "Tamil Nadu"},
	{City: "Pudukkottai", State: "Tamil Nadu"},
	{City: "Pudupattinam", State: "Tamil Nadu"},
	{City: "Puliyankudi", State: "Tamil Nadu"},
	{City: "Punjaipugalur", State: "Tamil Nadu"},
	{City: "Rajapalayam", State: "Tamil Nadu"},
	{City: "Ramanathapuram", State: "Tamil Nadu"},
	{City: "Rameshwaram", State: "Tamil Nadu"},
	{City: "Rasipuram", State: "Tamil Nadu"},
	{City: "Salem", State: "Tamil Nadu"},
	{City: "Sankarankoil", State: "Tamil Nadu"},
	{City: "Sankari", State: "Tamil Nadu"},
	{City: "Sathyamangalam", State: "Tamil Nadu"},
	{City: "Sattur", State: "Tamil Nadu"},
	{City: "Shenkottai", State: "Tamil Nadu"},
	{City: "Sholavandan", State: "Tamil Nadu"},
	{City: "Sholingur", State: "Tamil Nadu"},
	{City: "Sirkali", State: "Tamil Nadu"},
	{City: "Sivaganga", State: "Tamil Nadu"},
	{City: "Sivagiri", State: "Tamil Nadu"},
	{City: "Sivakasi", State: "Tamil Nadu"},
	{City: "Srivilliputhur", State: "Tamil Nadu"},
	{City: "Surandai", State: "Tamil Nadu"},
	{City: "Suriyampalayam", State: "Tamil Nadu"},
	{City: "Tenkasi", State: "Tamil Nadu"},
	{City: "Thammampatti", State: "Tamil Nadu"},
	{City: "Thanjavur", State: "Tamil Nadu"},
	{City: "Tharamangalam", State: "Tamil Nadu"},
	{City: "Tharangambadi", State: "Tamil Nadu"},
	{City: "Theni Allinagaram", State: "Tamil Nadu"},
	{City: "Thirumangalam", State: "Tamil Nadu"},
	{City: "Thirunindravur", State: "Tamil Nadu"},
	{City: "Thiruparappu", State: "Tamil Nadu"},
	{City: "Thirupuvanam", State: "Tamil Nadu"},
	{City: "Thiruthuraipoondi", State: "Tamil Nadu"},
	{City: "Thiruvallur", State: "Tamil Nadu"},
	{City: "Thiruvarur", State: "Tamil Nadu"},
	{City: "Thoothukudi", State: "Tamil Nadu"},
	{City: "Thuraiyur", State: "Tamil Nadu"},
	{City: "Tindivanam", State: "Tamil Nadu"},
	{City: "Tiruchendur", State: "Tamil Nadu"},
	{City: "Tiruchengode", State: "Tamil Nadu"},
	{City: "Tiruchirappalli", State: "Tamil Nadu"},
	{City: "Tirukalukundram", State: "Tamil Nadu"},
	{City: "Tirukkoyilur", State: "Tamil Nadu"},
	{City: "Tirunelveli", State: "Tamil Nadu"},
	{City: "Tirupathur", State: "Tamil Nadu"},
	{City: "Tirupathur", State: "Tamil Nadu"},
	{City: "Tiruppur", State: "Tamil Nadu"},
	{City: "Tiruttani", State: "Tamil Nadu"},
	{City: "Tiruvannamalai", State: "Tamil Nadu"},
	{City: "Tiruvethipuram", State: "Tamil Nadu"},
	{City: "Tittakudi", State: "Tamil Nadu"},
	{City: "Udhagamandalam", State: "Tamil Nadu"},
	{City: "Udumalaipettai", State: "Tamil Nadu"},
	{City: "Unnamalaikadai", State: "Tamil Nadu"},
	{City: "Usilampatti", State: "Tamil Nadu"},
	{City: "Uthamapalayam", State: "Tamil Nadu"},
	{City: "Uthiramerur", State: "Tamil Nadu"},
	{City: "Vadakkuvalliyur", State: "Tamil Nadu"},
	{City: "Vadalur", State: "Tamil Nadu"},
	{City: "Vadipatti", State: "Tamil Nadu"},
	{City: "Valparai", State: "Tamil Nadu"},
	{City: "Vandavasi", State: "Tamil Nadu"},
	{City: "Vaniyambadi", State: "Tamil Nadu"},
	{City: "Vedaranyam", State: "Tamil Nadu"},
	{City: "Vellakoil", State: "Tamil Nadu"},
	{City: "Vellore", State: "Tamil Nadu"},
	{City: "Vikramasingapuram", State: "Tamil Nadu"},
	{City: "Viluppuram", State: "Tamil Nadu"},
	{City: "Virudhachalam", State: "Tamil Nadu"},
	{City: "Virudhunagar", State: "Tamil Nadu"},
	{City: "Viswanatham", State: "Tamil Nadu"},
	{City: "Agartala", State: "Tripura"},
	{City: "Badharghat", State: "Tripura"},
	{City: "Dharmanagar", State: "Tripura"},
	{City: "Indranagar", State: "Tripura"},
	{City: "Jogendranagar", State: "Tripura"},
	{City: "Kailasahar", State: "Tripura"},
	{City: "Khowai", State: "Tripura"},
	{City: "Pratapgarh", State: "Tripura"},
	{City: "Udaipur", State: "Tripura"},
	{City: "Achhnera", State: "Uttar Pradesh"},
	{City: "Adari", State: "Uttar Pradesh"},
	{City: "Agra", State: "Uttar Pradesh"},
	{City: "Aligarh", State: "Uttar Pradesh"},
	{City: "Allahabad", State: "Uttar Pradesh"},
	{City: "Amroha", State: "Uttar Pradesh"},
	{City: "Azamgarh", State: "Uttar Pradesh"},
	{City: "Bahraich", State: "Uttar Pradesh"},
	{City: "Ballia", State: "Uttar Pradesh"},
	{City: "Balrampur", State: "Uttar Pradesh"},
	{City: "Banda", State: "Uttar Pradesh"},
	{City: "Bareilly", State: "Uttar Pradesh"},
	{City: "Chandausi", State: "Uttar Pradesh"},
	{City: "Dadri", State: "Uttar Pradesh"},
	{City: "Deoria", State: "Uttar Pradesh"},
	{City: "Etawah", State: "Uttar Pradesh"},
	{City: "Fatehabad", State: "Uttar Pradesh"},
	{City: "Fatehpur", State: "Uttar Pradesh"},
	{City: "Fatehpur", State: "Uttar Pradesh"},
	{City: "Greater Noida", State: "Uttar Pradesh"},
	{City: "Hamirpur", State: "Uttar Pradesh"},
	{City: "Hardoi", State: "Uttar Pradesh"},
	{City: "Jajmau", State: "Uttar Pradesh"},
	{City: "Jaunpur", State: "Uttar Pradesh"},
	{City: "Jhansi", State: "Uttar Pradesh"},
	{City: "Kalpi", State: "Uttar Pradesh"},
	{City: "Kanpur", State: "Uttar Pradesh"},
	{City: "Kota", State: "Uttar Pradesh"},
	{City: "Laharpur", State: "Uttar Pradesh"},
	{City: "Lakhimpur", State: "Uttar Pradesh"},
	{City: "Lal Gopalganj Nindaura", State: "Uttar Pradesh"},
	{City: "Lalganj", State: "Uttar Pradesh"},
	{City: "Lalitpur", State: "Uttar Pradesh"},
	{City: "Lar", State: "Uttar Pradesh"},
	{City: "Loni", State: "Uttar Pradesh"},
	{City: "Lucknow", State: "Uttar Pradesh"},
	{City: "Mathura", State: "Uttar Pradesh"},
	{City: "Meerut", State: "Uttar Pradesh"},
	{City: "Modinagar", State: "Uttar Pradesh"},
	{City: "Muradnagar", State: "Uttar Pradesh"},
	{City: "Nagina", State: "Uttar Pradesh"},
	{City: "Najibabad", State: "Uttar Pradesh"},
	{City: "Nakur", State: "Uttar Pradesh"},
	{City: "Nanpara", State: "Uttar Pradesh"},
	{City: "Naraura", State: "Uttar Pradesh"},
	{City: "Naugawan Sadat", State: "Uttar Pradesh"},
	{City: "Nautanwa", State: "Uttar Pradesh"},
	{City: "Nawabganj", State: "Uttar Pradesh"},
	{City: "Nehtaur", State: "Uttar Pradesh"},
	{City: "NOIDA", State: "Uttar Pradesh"},
	{City: "Noorpur", State: "Uttar Pradesh"},
	{City: "Obra", State: "Uttar Pradesh"},
	{City: "Orai", State: "Uttar Pradesh"},
	{City: "Padrauna", State: "Uttar Pradesh"},
	{City: "Palia Kalan", State: "Uttar Pradesh"},
	{City: "Parasi", State: "Uttar Pradesh"},
	{City: "Phulpur", State: "Uttar Pradesh"},
	{City: "Pihani", State: "Uttar Pradesh"},
	{City: "Pilibhit", State: "Uttar Pradesh"},
	{City: "Pilkhuwa", State: "Uttar Pradesh"},
	{City: "Powayan", State: "Uttar Pradesh"},
	{City: "Pukhrayan", State: "Uttar Pradesh"},
	{City: "Puranpur", State: "Uttar Pradesh"},
	{City: "Purquazi", State: "Uttar Pradesh"},
	{City: "Purwa", State: "Uttar Pradesh"},
	{City: "Rae Bareli", State: "Uttar Pradesh"},
	{City: "Rampur", State: "Uttar Pradesh"},
	{City: "Rampur Maniharan", State: "Uttar Pradesh"},
	{City: "Rasra", State: "Uttar Pradesh"},
	{City: "Rath", State: "Uttar Pradesh"},
	{City: "Renukoot", State: "Uttar Pradesh"},
	{City: "Reoti", State: "Uttar Pradesh"},
	{City: "Robertsganj", State: "Uttar Pradesh"},
	{City: "Rudauli", State: "Uttar Pradesh"},
	{City: "Rudrapur", State: "Uttar Pradesh"},
	{City: "Sadabad", State: "Uttar Pradesh"},
	{City: "Safipur", State: "Uttar Pradesh"},
	{City: "Saharanpur", State: "Uttar Pradesh"},
	{City: "Sahaspur", State: "Uttar Pradesh"},
	{City: "Sahaswan", State: "Uttar Pradesh"},
	{City: "Sahawar", State: "Uttar Pradesh"},
	{City: "Sahjanwa", State: "Uttar Pradesh"},
	{City: "Saidpur", State: " Ghazipur"},
	{City: "Sambhal", State: "Uttar Pradesh"},
	{City: "Samdhan", State: "Uttar Pradesh"},
	{City: "Samthar", State: "Uttar Pradesh"},
	{City: "Sandi", State: "Uttar Pradesh"},
	{City: "Sandila", State: "Uttar Pradesh"},
	{City: "Sardhana", State: "Uttar Pradesh"},
	{City: "Seohara", State: "Uttar Pradesh"},
	{City: "Shahabad", State: " Hardoi"},
	{City: "Shahabad", State: " Rampur"},
	{City: "Shahganj", State: "Uttar Pradesh"},
	{City: "Shahjahanpur", State: "Uttar Pradesh"},
	{City: "Shamli", State: "Uttar Pradesh"},
	{City: "Shamsabad", State: " Agra"},
	{City: "Shamsabad", State: " Farrukhabad"},
	{City: "Sherkot", State: "Uttar Pradesh"},
	{City: "Shikarpur", State: " Bulandshahr"},
	{City: "Shikohabad", State: "Uttar Pradesh"},
	{City: "Shishgarh", State: "Uttar Pradesh"},
	{City: "Siana", State: "Uttar Pradesh"},
	{City: "Sikanderpur", State: "Uttar Pradesh"},
	{City: "Sikandra Rao", State: "Uttar Pradesh"},
	{City: "Sikandrabad", State: "Uttar Pradesh"},
	{City: "Sirsaganj", State: "Uttar Pradesh"},
	{City: "Sirsi", State: "Uttar Pradesh"},
	{City: "Sitapur", State: "Uttar Pradesh"},
	{City: "Soron", State: "Uttar Pradesh"},
	{City: "Suar", State: "Uttar Pradesh"},
	{City: "Sultanpur", State: "Uttar Pradesh"},
	{City: "Sumerpur", State: "Uttar Pradesh"},
	{City: "Tanda", State: "Uttar Pradesh"},
	{City: "Tanda", State: "Uttar Pradesh"},
	{City: "Tetri Bazar", State: "Uttar Pradesh"},
	{City: "Thakurdwara", State: "Uttar Pradesh"},
	{City: "Thana Bhawan", State: "Uttar Pradesh"},
	{City: "Tilhar", State: "Uttar Pradesh"},
	{City: "Tirwaganj", State: "Uttar Pradesh"},
	{City: "Tulsipur", State: "Uttar Pradesh"},
	{City: "Tundla", State: "Uttar Pradesh"},
	{City: "Unnao", State: "Uttar Pradesh"},
	{City: "Utraula", State: "Uttar Pradesh"},
	{City: "Varanasi", State: "Uttar Pradesh"},
	{City: "Vrindavan", State: "Uttar Pradesh"},
	{City: "Warhapur", State: "Uttar Pradesh"},
	{City: "Zaidpur", State: "Uttar Pradesh"},
	{City: "Zamania", State: "Uttar Pradesh"},
	{City: "Almora", State: "Uttarakhand"},
	{City: "Bazpur", State: "Uttarakhand"},
	{City: "Chamba", State: "Uttarakhand"},
	{City: "Dehradun", State: "Uttarakhand"},
	{City: "Haldwani", State: "Uttarakhand"},
	{City: "Haridwar", State: "Uttarakhand"},
	{City: "Jaspur", State: "Uttarakhand"},
	{City: "Kashipur", State: "Uttarakhand"},
	{City: "kichha", State: "Uttarakhand"},
	{City: "Kotdwara", State: "Uttarakhand"},
	{City: "Manglaur", State: "Uttarakhand"},
	{City: "Mussoorie", State: "Uttarakhand"},
	{City: "Nagla", State: "Uttarakhand"},
	{City: "Nainital", State: "Uttarakhand"},
	{City: "Pauri", State: "Uttarakhand"},
	{City: "Pithoragarh", State: "Uttarakhand"},
	{City: "Ramnagar", State: "Uttarakhand"},
	{City: "Rishikesh", State: "Uttarakhand"},
	{City: "Roorkee", State: "Uttarakhand"},
	{City: "Rudrapur", State: "Uttarakhand"},
	{City: "Sitarganj", State: "Uttarakhand"},
	{City: "Tehri", State: "Uttarakhand"},
	{City: "Muzaffarnagar", State: "Uttar Pradesh"},
	{City: "Adra", State: " Purulia"},
	{City: "Alipurduar", State: "West Bengal"},
	{City: "Arambagh", State: "West Bengal"},
	{City: "Asansol", State: "West Bengal"},
	{City: "Baharampur", State: "West Bengal"},
	{City: "Bally", State: "West Bengal"},
	{City: "Balurghat", State: "West Bengal"},
	{City: "Bankura", State: "West Bengal"},
	{City: "Barakar", State: "West Bengal"},
	{City: "Barasat", State: "West Bengal"},
	{City: "Bardhaman", State: "West Bengal"},
	{City: "Bidhan Nagar", State: "West Bengal"},
	{City: "Chinsura", State: "West Bengal"},
	{City: "Contai", State: "West Bengal"},
	{City: "Cooch Behar", State: "West Bengal"},
	{City: "Darjeeling", State: "West Bengal"},
	{City: "Durgapur", State: "West Bengal"},
	{City: "Haldia", State: "West Bengal"},
	{City: "Howrah", State: "West Bengal"},
	{City: "Islampur", State: "West Bengal"},
	{City: "Jhargram", State: "West Bengal"},
	{City: "Kharagpur", State: "West Bengal"},
	{City: "Kolkata", State: "West Bengal"},
	{City: "Mainaguri", State: "West Bengal"},
	{City: "Mal", State: "West Bengal"},
	{City: "Mathabhanga", State: "West Bengal"},
	{City: "Medinipur", State: "West Bengal"},
	{City: "Memari", State: "West Bengal"},
	{City: "Monoharpur", State: "West Bengal"},
	{City: "Murshidabad", State: "West Bengal"},
	{City: "Nabadwip", State: "West Bengal"},
	{City: "Naihati", State: "West Bengal"},
	{City: "Panchla", State: "West Bengal"},
	{City: "Pandua", State: "West Bengal"},
	{City: "Paschim Punropara", State: "West Bengal"},
	{City: "Purulia", State: "West Bengal"},
	{City: "Raghunathpur", State: "West Bengal"},
	{City: "Raiganj", State: "West Bengal"},
	{City: "Rampurhat", State: "West Bengal"},
	{City: "Ranaghat", State: "West Bengal"},
	{City: "Sainthia", State: "West Bengal"},
	{City: "Santipur", State: "West Bengal"},
	{City: "Siliguri", State: "West Bengal"},
	{City: "Sonamukhi", State: "West Bengal"},
	{City: "Srirampore", State: "West Bengal"},
	{City: "Suri", State: "West Bengal"},
	{City: "Taki", State: "West Bengal"},
	{City: "Tamluk", State: "West Bengal"},
	{City: "Tarakeswar", State: "West Bengal"},
	{City: "Chikmagalur", State: "Karnataka"},
	{City: "Davanagere", State: "Karnataka"},
	{City: "Dharwad", State: "Karnataka"},
	{City: "Gadag", State: "Karnataka"},
	{City: "Chennai", State: "Tamil Nadu"},
	{City: "Coimbatore", State: "Tamil Nadu"},
}
